### ISSUE TITLE
New images for offset example

### ISSUE THREAD

**Issue by eibanez** [twlare/WLEDDocs#1]
Hi,

I just started a pull request in WLED-docs to document offsets in segments: https://github.com/Aircoookie/WLED-Docs/pull/35

I think it would be helpful to have a couple additional images like this for that section:
![](https://github.com/twlare/WLEDDocs/raw/master/LEDS12.png)

Would you be able to create two additional files?
 - One with the labels being ```7 8 9 10 11 0 1 2 3 4 5 6```
 - Another one with ```2 3 4 5 6 7 8 9 10 11 0 1```

**Comment by twlare** [comment]
Yes, I can do this. Can you give me a day or two? Thanks.

**Comment by twlare** [comment]
I uploaded two new images which should match your request above.

LED7to6.png - 7, 8, ... 5, 6
LED2to1.png - 2, 3, ... 0, 1

Can you link to those images in your documentation or do they need to be in
your account?
(Sorry, I don't really know anything about GitHub)

**Comment by eibanez** [comment]
I can link to them. Thanks!
